### ISSUE TITLE
「ユーザーを管理する」の意味合いがわかりにくかった

### ISSUE THREAD

**Issue by ueponx** [taijihagino/low-code-dev#1]
ファイル： IDEと静的Webアプリ.md

末尾にあるユーザーを管理の部分がどういう用途で使用されるのかがわかりにくかったので、
開発者とは別にテストユーザーを作成して、テストができるという意味合いの説明があるとよいのではと思いました。
そのほかの機能もあれば補足していただければと思います。

また、Nameは日本語使用は問題ないですが、UserNameは日本語での登録はできるのですが、ログインはできない
点も追記いただければと思います。

**Comment by taijihagino** [comment]
@ueponx 修正対応しました。ご指摘ありがとうございました。
