### ISSUE TITLE
Publish処理の強調表示

### ISSUE THREAD

**Issue by ueponx** [taijihagino/low-code-dev#2]
ファイル：3. サイトプロパティによるランタイム設定.md

＞３．WhatToSayのMessageをダブルクリックし編集ウィンドウを表示します。ハードコーディングしていた「"こんにちは、"」を削＞除し、Scope → OnClick → GetWhatToSay配下の「WhatToSay」をダブルクリックしてリテラル文字列が合った部分に設定します。最＞後に「Close」ボタンをクリックします。ここで、Publishもしておきましょう。

上記の部分の最後に【Publish】を行うのを忘れてしまったので、強調をしていただけるとわかりやすくなると思います。

**Comment by taijihagino** [comment]
@ueponx 対応しました。ご意見ありがとうございました。
