### ISSUE TITLE
評価演算子が説明と図が一致していない

### ISSUE THREAD

**Issue by ueponx** [taijihagino/low-code-dev#3]
ファイル： 4. 文字列検索を使ったフォームバリデーション.md

説明文中の下記

＞関数の結果を評価するために式を書きます。評価演算子は「<=」として、右辺は「0」にします。

説明の図の評価演算子と異なっています。図中の「>=」が正しいです。

**Comment by taijihagino** [comment]
@ueponx ご指摘ありがとうございます。演算子の説明を修正いたしました。
